/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Article: typeof import('./src/components/Article.vue')['default']
    Aside: typeof import('./src/components/Aside.vue')['default']
    BackToTop: typeof import('./src/components/BackToTop.vue')['default']
    Datacard: typeof import('./src/components/admin/datacard.vue')['default']
    DuxiuIndex: typeof import('./src/components/DuxiuIndex.vue')['default']
    DuxiuIndexAside: typeof import('./src/components/DuxiuIndexAside.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ErrorSkeleton: typeof import('./src/components/ErrorSkeleton.vue')['default']
    LoadingSkeleton: typeof import('./src/components/LoadingSkeleton.vue')['default']
    MainNav: typeof import('./src/components/MainNav.vue')['default']
    Message: typeof import('./src/components/Messge/Message.vue')['default']
    Photo: typeof import('./src/components/Photo.vue')['default']
    PhotoDetail: typeof import('./src/components/PhotoDetail.vue')['default']
    PoemAside: typeof import('./src/components/PoemAside.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
