/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Article: typeof import('./src/components/Article.vue')['default']
    Aside: typeof import('./src/components/Aside.vue')['default']
    BackToTop: typeof import('./src/components/BackToTop.vue')['default']
    DuxiuIndex: typeof import('./src/components/DuxiuIndex.vue')['default']
    DuxiuIndexAside: typeof import('./src/components/DuxiuIndexAside.vue')['default']
    ErrorSkeleton: typeof import('./src/components/ErrorSkeleton.vue')['default']
    LoadingSkeleton: typeof import('./src/components/LoadingSkeleton.vue')['default']
    MainNav: typeof import('./src/components/MainNav.vue')['default']
    Photo: typeof import('./src/components/Photo.vue')['default']
    PhotoDetail: typeof import('./src/components/PhotoDetail.vue')['default']
    PoemAside: typeof import('./src/components/PoemAside.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
