import { createApp } from "vue";
import App from "./App.vue";
import "./style/theme.less";
import router from "./router";
import mitt from "mitt";
import { VueMasonryPlugin } from "vue-masonry";
import { createPinia } from "pinia";
import piniaPluginPersistedstate from "pinia-plugin-persistedstate";
const app = createApp(App);
const emitter = mitt();
app.config.globalProperties.emitter = emitter;
const pinia = createPinia();
pinia.use(piniaPluginPersistedstate);
app.use(pinia);
app.use(VueMasonryPlugin);
app.use(router);
app.mount("#app");
