/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    'IconFluent:contentView24Regular': typeof import('~icons/fluent/content-view24-regular')['default']
    'IconIc:outlineHome': typeof import('~icons/ic/outline-home')['default']
    'IconTabler:photo': typeof import('~icons/tabler/photo')['default']
    IconTablerUserCircle: typeof import('~icons/tabler/user-circle')['default']
    MaxBar: typeof import('./src/components/MaxBar.vue')['default']
    MaxButton: typeof import('./src/components/MaxButton.vue')['default']
    MaxInput: typeof import('./src/components/MaxInput.vue')['default']
    MaxTable: typeof import('./src/components/MaxTable/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
